import type { Metadata } from "next";
import { inter } from "@/app/ui/fonts";
import "./globals.css";
import Sidenav from "@/app/ui/navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={` h-full antialiased`}
    >
      <body className={`${inter.className} min-h-full flex flex-col`}>
        <Sidenav />
        {children}
      </body>
    </html>
  );
}
